README.md
I guess many people don't know what it is.
=> Add Yarn resolutions link

template/src/index.ts, template/test/blah.test.ts
=> replace f**k in template

package.json, src/createJestConfig.ts, src/createRollupConfig.ts, src/env.d.ts, src/getInstallArgs.ts, src/getInstallCmd.ts, src/index.ts, src/logError.ts, src/messages.ts, src/output.ts, src/utils.ts, tsconfig.json
This at least starts us down the path...
=> Turn on noImplicitAny

src/createRollupConfig.ts
closes https://github.com/palmerhq/tsdx/issues/36
=> opt out of collapse_vars in terser, because it is buggy

src/createJestConfig.ts
Needed for compatibility with [Visual Studio Code - Jest extension](https://github.com/jest-community/vscode-jest)
=> Write Jest configuration file

src/index.ts, templates/basic/tsconfig.json, templates/react/tsconfig.json
=> feat: use tslib by default

templates/react/example/package.json
use parcel's aliasing for react template example deps. closes https://github.com/palmerhq/tsdx/issues/64
=> use parcel's aliasing for react template example deps

README.md
i had this in my React Guide PR but it belongs at the top level - submitting as PR for review
=> document rollup config treeshaking

templates/react/README.md
As discussed in #116, added documentation to mention a known caveat when using the react template with lerna
=> Document react template usage with lerna

src/index.ts
=> Fix --format=es

src/index.ts
=> Add spiffy ascii art to tsdx create

package.json, src/utils.ts, test/jest.config.json, test/tests/utils-safePackageName.test.ts, yarn.lock
=> strip package scope in safePackageName function

templates/react/example/index.html
Hey there :wave: Thanks for this awesome package!
---
Pretty minor diff, but [`react-live`](https://github.com/FormidableLabs/react-live) was having weird rendering issues without it.
Only discovered because I was porting an already functioning example, without any code changes.
I can also run prettier on this file if preferred.
`vscode` ends up auto-formatting it on save.
=> Add doctype to react template html file

templates/react/README.md
as suggested in https://github.com/palmerhq/tsdx/issues/156
add netlify deploy instructions to react readme
=> add netlify deploy instructions to react readme

package.json, yarn.lock
=> update babel-plugin-transform-async-to-promises dependency

src/babelPluginTsdx.ts
=> Don't replace imports in cjs build

test/tests/lint/tsdx-lint.test.js
=> Attempt to fix lint test

templates/basic/tsconfig.json, templates/react/tsconfig.json
Fixes https://github.com/jaredpalmer/tsdx/issues/225
=> Add "test" to include key in template tsconfigs

package.json
=> Remove TS as peer dep

package.json, yarn.lock
https://github.com/jaredpalmer/tsdx/pull/362/ failed on windows, trying an incremental upgrade strategy
=> update to ts 3.7

package.json, src/babelPluginTsdx.ts, test/fixtures/build-default/src/index.ts, test/fixtures/build-default/src/syntax/nullish-coalescing.ts, test/fixtures/build-default/src/syntax/optional-chaining.ts, yarn.lock
=> Add optional chaining and nullish coalescing operators support

README.md
Taken from here: https://github.com/jaredpalmer/tsdx/issues/319#issuecomment-566659469
=> [docs] howto turn off watch mode

src/index.ts
- better readability / changeability
Something I changed in the process of fixing types for #401
=> (refactor): invert if in run function

templates/basic/.github/workflows/main.yml, templates/react-with-storybook/.github/workflows/main.yml, templates/react/.github/workflows/main.yml
In action [here](https://github.com/OperationCode/components/pull/7)
Also, it would be nice if we could have a folder for like "goes in all templates"... I would hate to see one of the files get updated in one template, but not the others.
=> Add GH Action configs for each template

package.json
Reverts jaredpalmer/tsdx#462
we are still on jest 24, sorry
=> Revert "chore(package): update @types/jest to version 25.1.0 (#462)"

src/index.ts
- it does the same thing as those two combined
Similar to my previous #406 etc. Found this while reviewing #277
=> (refactor): use outputFile instead of mkdirs + writeFile

package.json, yarn.lock
=> Add publish npm script

package.json
`yarn upgradeInteractive` shows the homepage url and falls back to other urls.
=> [docs] add homepage to package.json

src/messages.ts
Not sure how you feel about this, but it surely took me by surprise the first time ("Have I installed the wrong package?")
=> (fix): update messages.ts github links to formik/ org

README.md, website/pages/optimization.mdx
Add a missing "to" infinitive marker.
=> docs/fix: missing "to" infinitive marker
