- package.json
- src/index.js
- Add prettier, husky, and lint-staged to the template's package.json
Close #43
> Add prettier to template

- .circleci/config.yml
- package.json
- src/createJestConfig.js
- src/createRollupConfig.js
- src/index.js
- test/fixtures/build-default/package.json
- test/fixtures/build-default/src/index.ts
- test/fixtures/build-default/test/blah.test.ts
- test/fixtures/build-default/tsconfig.json
- test/fixtures/util.js
- test/jest.config.json
- test/tests/tsdx-build.test.js
- test/utils/psKill.js
- tsconfig.json
- yarn.lock
- Upgrade to Jest 24 and latest ts-jest
- AFAICT `ts-jest` with the typescript compiler doesn't fully support Jest 24 yet?? so there is a warning message. Also `ts-jest` doesn't provide a single file jest transformer anymore so we cannot use `require.resolve` to point to the location of that file in our `createJestConfig`. This is super weird. CRA avoids this because it uses the babel version.
- Add internal tests!
> Upgrade to jest 24 + ts-jest

- package.json
- yarn.lock
`lint-staged` is [11.5MB](https://packagephobia.now.sh/result?p=lint-staged)
`pretty-quick` is [0.4MB](https://packagephobia.now.sh/result?p=pretty-quick)
And `lint-staged` depends on at least one unmaintained package.
> feat: use pretty-quick

- src/getInstallArgs.js
- src/index.js
If yarn is not install, this should fallback to npm.
Close #48
> Use npm, if yarn is not installed

- src/index.js
The "prepare" script is executed not only when `yarn` is run, but also when any dependency is installed, so its more annoying than useful.
> build: remove "prepare" script

- package.json
- src/index.js
- yarn.lock
If a folder of the same name already exists in the directory, we now gracefully ask for a new project name (recursively).
Close #44
> Gracefully prompt if folder exists already

- src/index.ts
- Ensure that the CommonJS entry file is properly generated in `watch` cmd.
- Ensure that filenames match `build` cmd. Fixes #35
> Create an entry file during watch cmd

- src/createJestConfig.ts
The problem occured in #62 and seems to come from this part: `?(*.)`.
Applying the changes in this PR finds the files correctly and runs tests for `.ts` and `.tsx` files inside root and subfolders within `/test/`.
Can't check if this still works on other OS than Windows though. 
```
PS C:\dev\hidash> npm test
> hidash@0.1.0 test C:\dev\hidash
> tsdx test
PASS  test/blah.test.ts
PASS  test/fix/make.test.tsx
Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        3.362s
Ran all test suites.
```
> Fix testMatch to find test files correctly

- README.md
- src/createRollupConfig.ts
This is using Jest v24 not v23.
From the create command:
```js
scripts: {
start: 'tsdx watch',
build: 'tsdx build',
test: template === 'react' ? 'tsdx test --env=jsdom' : 'tsdx test',
```
So it's wasn't necessary to say
> If you are trying to test a React component, you likely want to pass in `--env=jsdom` just like you do in Create React App
Proposed:
> If you are using the React template, jest uses the flag `--env=jsdom` by default.
> docs(readme): specify Jest v24 is used.  Clarify jsdom flag

- src/index.ts
Fixes https://github.com/palmerhq/tsdx/issues/76
I wasn't sure how to write a test for this. Sorry. I'd be happy to write a test if you point me to an example of a similar test that it should look like.
Details copied from commit message: 
> fix: remove falsey build configs
>
> If the `opts.format.includes` call above returns false, a `false` value
> is inserted into the array in place of a rollup config object. Each
> element of the `createBuildConfigs` is eventually passed into rollup
> as an `inputOption`. If one of these elements is `false`, the script will
> pass that value as a config to rollup which results in a rollup error
> stating: "You must supply an options object to rollup"
>
> This commit fixes that issue by filtering out falsey values.
> Filter falsey values from build configs before passing them to rollup

- src/utils.ts
- test/fixtures/build-default/src/foo.ts
- test/fixtures/build-default/src/index.ts
- test/tests/tsdx-build.test.js
Fixes #87 
Absolute path detection was not working for Windows users. I updated the util to use Node's built-in function.
I also created a regression test in the testing suite to ensure that exports defined in other files are correctly included in the final library build.
> fix external module detection on Windows

- src/createJestConfig.ts
I actually do not think we should even be writing this file. We need to resolve to tsdx's versions of ts-jest so that our users do not have to. This means that this will cause pain with hard coded paths (#90)
> Remove writing to jest config

- templates/react/example/package.json
having a yarn build command makes it easier to deploy example to CI, as start is watch mode
> add "yarn build" for example

- src/createRollupConfig.ts
- src/env.d.ts
Fixes https://github.com/palmerhq/tsdx/issues/95
>rollup-plugin-typescript2 transpiles the code but doesn't change the
file extensions. Files with ts and tsx extentions aren't processed by
Babel by default so we need to add those extensions to the babel config.
I'm not actually using tsdx on a production app (yet? we need to be able to configure babel though 😕) so I don't have a great way to test this with confidence for a real world project. 
Also I'm seeing...
> Module '"../../../../../../Users/jake/Code/jakegavin/tsdx/node_modules/@types/babel__core"' has no exported member 'DEFAULT_EXTENSIONS'
But its [there](https://github.com/babel/babel/blob/1969e6b6aa7d90be3fbb3aca98ea96849656a55a/packages/babel-core/src/index.js#L39-L45). I guess it's maybe not in the [babel core …
> Explicitly specify ts and tsx extensions in babel options

- README.md
First pass at documenting the built-in optimizations. Did not proof read. So feel free to nitpick typos 
cc @sw-yx 
Closes #8.
> Document some of the optimizations

- src/createRollupConfig.ts
Fixes https://github.com/palmerhq/tsdx/issues/101
The config for the typescript rollup plugin had an `esnext` override for the `target`, so files weren't getting compiled down.  Set a default to `es5` that can be overridden by the `tsconfig` at the project level.
> Remove Typescript "esnext" target override from rollup config.

- package.json
- src/createRollupConfig.ts
> @babel/preset-env

- templates/react/gitignore
The React template has a `.gitignore` file at the root of the project and an additional `.gitignore` in the `/example` playground directory.
Locally, the `/example/.gitignore` file was ignored, causing the `/example/.cache` directory to be committed. 
This PR adds `.cache` to the root `.gitignore` file to avoid this problem.
> Fix React template .gitignore

- src/createRollupConfig.ts
- src/index.ts
It seems working for `build` and `watch` commands. I will need help for `test`.
example commands with `tsconfig` flag
`tsdx build --tsconfig ./tsconfig.foo.json`
`tsdx watch --tsconfig ./tsconfig.foo.json`
> feat(custom-tsconfig): Add ability to specify custom tsconfig.json

- README.md
- src/index.ts
- test/tests/tsdx-build.test.js
With this pr `tsdx build` command no longer build `umd` format as default. But still `tsdx build --format umd` can be used for umd builds. #120 
I have deleted `umd` output related tests. Should we add test cases for different format combinations?
> Remove UMD format from default build outputs

- package.json
I've run into the issue where I have TS 3.2 in the workspace where I want to use TSDX compiled module. However, TSDX got installed with 3.5.2 and compiles with that version. There are some breaking changes between those versions.
I could surely use Yarn resolutions to overcome that, but that's hardly a scalable solution. So I propose this change to let the user decide on the TS version.
> Don't depend on specific TS version

- templates/basic/gitignore
- templates/react/gitignore
This is the issue mentioned in #148.
Tested with `yarn link` mentioned in [contribution guideline ](https://github.com/dance2die/tsdx/blob/master/CONTRIBUTING.md).
You can see that adding the tsdx created project to a git repo doesn't stage the "*.esm" folder.
> fixed issue mentioned in #148 - Gitignore contains '.rts2_cache_esm'

- src/index.ts
- test/fixtures/build-invalid/package.json
- test/fixtures/build-invalid/src/index.ts
- test/fixtures/build-invalid/tsconfig.json
- test/tests/tsdx-build.test.js
I found some problems with `build` command.
1. It does exit with code `0` even when the build failed. I think it should be `1`.
2. When it fails, the error won't be caught and that causes `UnhandledPromiseRejectionWarning`.
> Gracefully exit with code 1 when build failed

- src/index.ts
I want to run `tsdx create` from another program which means I can't fill in the template prompt.
I added an optional `--template` flag to the create command. 
The flag value is checked with the options available in the prompt. If invalid, the user is prompted to make a choice.
> Add template flag to create command

- README.md
- src/index.ts
Hey there!
Huge fan of `tsdx`, we currently use it to compile packages within our monorepo.
When running tsdx in watch mode, tsdx currently clears the console with no ability to retain the console output. This PR adds an opt-in ability to preserve the console output during watch. This PR behavior aligns with the existing TypeScript compiler option ( https://www.typescriptlang.org/docs/handbook/compiler-options.html, e.g. `tsc -w --preserveWatchOutput`).
As far as use cases, a common workflow inside a monorepo is to run all packages in watch mode using something like [`wsrun`](https://github.com/hfour/wsrun). Clearing the output makes it hard to debug or audit the logs if something goes wrong within the monorepo dependency chain on start up.
> Provide ability to preserve console output during watch

- src/createJestConfig.ts
I like to pair testing files with my source code files so everything is collocated in a file explorer. This shouldn't be a breaking change and will simply allow me to create test files outside of the initially created `test` folder.
> Update createJestConfig.ts `testMatch` to allow for other folder structures

- src/index.ts
- Fixes the husky pre-commit hook not using the `tsdx lint` command
- Fixes `tsdx lint` without any input files failing with a help message instead of silently appearing to succeed.
Related to #7
@skvale also curious about your 👀 in case I missed something.
> Fix lint command usage by husky and required files

- README.md
Very minor change. Almost didn't bother but I will say that I incorrectly assumed the project was using TSLint for a while due to this remark in the readme.
> Update readme to reference eslint instead of tslint.

- src/index.ts
- test/tests/lint/tsdx-lint.test.js
Currently if you try `tsdx lint --write-file` you get:
```sh
Description
Run eslint with Prettier
Usage
$ tsdx lint [options]
Options
--fix               Fixes fixable errors and warnings
--ignore-pattern    Ignore a pattern
--write-file        Write the config file locally
-h, --help          Displays this message
Examples
$ tsdx lint src test
$ tsdx lint src test --fix
$ tsdx lint src test --ignore-pattern test/foobar.ts
$ tsdx lint --write-file
No input files specified.
```
> Fix lint command by allowing use --write-file flag

- .github/workflows/nodejs.yml
- test/jest.config.json
Based on some conversations at React Native EU, tsdx is gaining some users inside of Microsoft. To better support them, this PR updates our GitHub Actions to run the test suite on Node 8, 10, 12 in macOS, windows, and ubuntu.
> Run tests against Node/OS version matrix

- templates/react/README.md
Lib needs to be built to `dist` before example can be built ("Cannot resolve dependency '../../dist'")
> [Deploy Playground] Fix Netlify build command

- src/index.ts
> Use `['src', 'test']` as default input files for lint

- src/index.ts
- test/tests/lint/tsdx-lint.test.js
1. remove `aynsc` from `lint` CLI command. having `async` there swallows errors, and isn't necessary because no `await` is used.
2. tests were broken, fixed.
> remove async; fix test

- .gitignore
- README.md
- src/index.ts
- src/types.ts
- templates/basic/gitignore
- templates/react/gitignore
- website/docs/customization.md
We need support for SystemJS format because we would like to load generated bundle through SystemJS.
Hopefully, I haven't missed changing something. :blush: 
I've tested just basic scenario and it seems okay. Not sure how to test it on some complex scenario.
> Add system to list of supported formats

- src/constants.ts
- src/index.ts
Currently, `jest.config.js` is ignored. My fix is to try and check if there is a `jest.config.js`, if so then we just merge it into the jestConfig. 
This fixes #100 . 
Issue #150 is in a similar vein to this but that needs some more work.
> fix(testing): add support for jest.config.js

- .github/workflows/nodejs.yml
Using the `--ignore-engines` flag when installing with yarn https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-ignore-engines
This is necessitated by one of the deps we rely on, `rollup-plugin-ts`, having a node >= 9.0.0 engine requirement which is failing the nodejs 8 builds.
https://github.com/wessberg/rollup-plugin-ts/blob/9079d7a4705078e0709a6f5b9b5147081cce7baf/package.json#L108-L110
To view the github actions error see https://github.com/jaredpalmer/tsdx/runs/259520250#step:5:7
> fix: failing builds

- src/index.ts
- Use `paths.appDist` in places where we need to refer to the `dist` folder.
> Use dist path config

- src/constants.ts
- src/index.ts
- Moved storage path into paths configuration
- Fixed progress logger integration. It creates the storage folder since `.cache` folder inside `node_modules` may be missing and the package doesn't resolve this issue
> Fix logger integration

- src/constants.ts
- src/createProgressEstimator.ts
- src/index.ts
This only creates the progress estimator cache during `tsdx build` instead of on every single run. It also makes is async.
Continuation of #256
> Lazily initialize progress estimator cache

- README.md
- src/index.ts
I've added new flag `--report-file report.json` to `tsdx lint` which is the same as `eslint -f json -o report.json`.
e.g. `tsdx lint src --report-file report.json`
> Added support for eslint report

- README.md
- src/index.ts
When using the lib in development in a yarn workspace, the first step to clean the dist folder trigger the webpack watcher (of CRA or react-native for example) which fail to recompile. This option will enable the smoother workflow for developing side by side a library with an app. 
Related discussions:
- https://github.com/jaredpalmer/tsdx/pull/272#issuecomment-543836283
- https://github.com/jaredpalmer/tsdx/issues/223#issuecomment-541956974
Notes:
- I didn't add it for build because I don't see any use case for that.
- I choose `--noClean` instead of `--no-clean` for consistency with `--extractErrors`
> --noClean option for watch

- src/createProgressEstimator.ts
The line removed didn't make sense in the context of this source.
It appears to have been copied from https://github.com/bvaughn/progress-estimator/blob/master/README.md#usage-example (in the context of the README it made more sense).
> Remove confusing comment

- src/createEslintConfig.ts
- src/index.ts
- src/types.ts
- src/utils.ts
**Current behavior:**
We get a warning about detecting React version using the `lint` command in non-react projects.
**New behavior:**
Using the shared settings and the same value used by `eslint-plugin-react` [internally](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/util/version.js#L29) - it could be almost any value, but I chose this one, we don't get the warning on non-react projects. Closes #279.
**How to reproduce:**
- Use `tsdx lint` inside a react and a non-react project;
- No warning is displayed on both cases.
**Notes:**
N/A.
> fix(lint): do not output warning about react on non-react projects

- src/babelPluginTsdx.ts
Adding `@babel/preset-env` without options to `.babelrc` will cause an error
`.babelrc`
```json
{
"presets": ["@babel/preset-env"]
}
```
**Error**
```
✖ Failed to compile
(babel plugin) TypeError: Cannot read property 'exclude' of undefined
TypeError: Cannot read property 'exclude' of undefined
at Object.config (/Users/jirat.ki/Code/lab/tsdxLib/node_modules/tsdx/dist/babelPluginTsdx.js:98:127)
at Object.transform (/Users/jirat.ki/Code/lab/tsdxLib/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:197:26)
at /Users/jirat.ki/Code/lab/tsdxLib/node_modules/rollup/dist/rollup.js:12084:25
```
> Fix error when adding `@babel/preset-env` without options

- src/index.ts
- test/tests/lint/tsdx-lint.test.js
> fix(lint): Only default to src test if they exist

- .gitignore
- src/createRollupConfig.ts
- templates/basic/gitignore
- templates/react/gitignore
- instead of outputting these to app root and requiring users to
gitignore these directories, just output to node_modules/.cache/
- rollup-plugin-typescript2 is the default cache directory [1], so this
initially appended _${opts.format} to it
- upon code review, changed it to tsdx/${opts.format}/
- babel-loader similarly uses node_modules/.cache/babel-loader [2]
as its default cache directory and does not allow users to
change it
- parcel uses node_modules/.cache/parcel too [3]
- fuse-box uses node_modules/.fusebox [4]
[1]: https://github.com/ezolenko/rollup-plugin-typescript2#plugin-options > `cacheRoot`
[2]: https://github.com/babel/babel-loader#options > `cacheDirectory`
[3]: https://github.com/parcel-bundler/parcel#caching
[4]: …
> (change): use node_modules/.cache/... as cacheRoot

- src/createEslintConfig.ts
- src/createRollupConfig.ts
- src/errors/extractErrors.ts
- src/getInstallCmd.ts
- src/index.ts
- src/messages.ts
See #265 
I removed most of the sync functions, there are some scenarios which I am unsure what to do. For instance, those sync calls that are at module level (like `src/index.ts` line 50 or line 60)
Same for `src/errors/transformErrorMessages.ts` - I am unsure if I can make that function async
Still pending one change from `getProjectPath()` in `src/index.ts`
> Replaced some sync methods for their async version

- .github/workflows/nodejs.yml
this command is breaking the windows build for our CI and causing a lot of greenkeeper false positives. and based on [this](https://github.com/actions/setup-node/commit/57adacb752d56f434eed924bad6ef995a163861b) doesnt seem to be necessary
making this a PR in case this works for github
> Remove unnecessary yarn install command in GH action

- src/errors/extractErrors.ts
#291 replaced all instances of `sync` versions of some methods with their corresponding `async` versions. Updated the comment accordingly.
> fix(chore): fixed minor typo

- src/createRollupConfig.ts
- the previous assumption that ESM users will always import the ESM
build doesn't actually hold up in practice due to various limitations
in Node and testing and the prevalence of transpiling in general
- even if one uses mostly ESM, many tools will require and use
the CJS build, and this option would break compatibility
- without esModule set, CJS users would be unable to use the default
export of any library built with tsdx
- and this was not documented, meaning it would cause unintended
breaking changes in libraries that use default exports and try to
adopt tsdx
- it would also break compatibility with certain tooling
- so, instead of always setting rollup's esModule to false and
potentially causing unintended consequences, respect the user's
esModuleInterop config as set in their …
> (fix): respect tsconfig esModuleInterop flag

- src/index.ts
fixes https://github.com/jaredpalmer/tsdx/issues/319
> default jest to watch mode when not in CI

- .gitignore
- README.md
- package.json
- src/index.ts
The prepare script runs before publishing to npm and when the module is installed as a git dependency.
> Add prepare script to generated project

- src/index.ts
It doesn't seem like GH Actions / CI are running for each PR, as no status checks appear for them --    probably why #366 slipped through. I'm not sure why they're not running, looks normal to me though I've never used GH Actions before for CI.
> (fix/format): formatting of #366 didn't pass lint

- .github/workflows/nodejs.yml
- previously would only run on branches from origin, so PRs from a
fork would not trigger them
Follow up to #372 once I took a look at the GH Actions docs. @sw-yx GH Actions were probably working for your use case because you were using branches on this repo and not from a fork during your PRs. The Actions are running in this PR from my fork now.
Now _oddly enough_, #366 did run the Actions (being an origin branch), and [_somehow they passed???_](https://github.com/jaredpalmer/tsdx/pull/366/checks?check_run_id=343558866). I have no idea why the lint test didn't fail 😳 
Also as a follow-up to this -- you probably want to add branch protection rules for `master` so the checks are required before passing. This would also make it easier to detect when there's a CI logic bug.
> (fix/ci): GitHub Actions should run on PRs as well

- templates/react-with-storybook/gitignore
- these are no longer necessary after my cacheRoot changes
#318 copied the gitignore from the other examples at the time, but my PR at #329 was merged earlier, which means those directories no longer exist
> (clean): remove .rts_cache_* from storybook gitignore

- .github/workflows/nodejs.yml
- a few recent PRs got in without passing lint, this breaks all future
PRs/branches/commits because pre-commit will fail when it runs lint
Turns out `lint` was never running in CI! Which explains why #370 and #366 passed (and my confusion in #373 )
This should make formatting fixes like #372 and #377 unnecessary in the future if only PRs that pass lint are merged.
I limited this to run on Node v10 and `ubuntu-latest` -- not sure if a matrix is necessary for self-linting. The existing test suite already has tests for `tsdx lint` and that runs over the matrix ofc.
> (ci): add a lint job so PRs will require passing lint

- src/createRollupConfig.ts
- src/index.ts
- treeshake was in output, but it's not a config of output :/ :/ :/
- once explicit types were added, this was a big red underline :/ :/
Yeaaaaaaaaa so that's kind of a problem 😕 😕 😕 Related to #365 and potentially related to #171. This bug has been around for a long enough time that it's fix may cause some breakage, idk.
Related: Does the `eslint` config error on getters and setters? That wouldn't help with imported code, but would at least reduce unexpected errors in one's own codebase.
Also should we add some regression tests for treeshaking? It's typed correctly _now_, but might make sense to have a test for something like this that could be considered critical and hard to catch, idk.
<hr>
I was going around adding types to builder code during #367 because type-checking would add a …
> (types/fix): explicit Rollup typing, fix treeshake location

- README.md
- it was not clearly stated that CI=true was what needed to be added,
so explicitly state that
- similarly, --color was an unnecessary option to pass and may have
caused confusion, potentially making users believe that it was
necessary in order to disable watch mode
- also, --color does not seem to be a valid option of Jest, but
[--colors](https://jestjs.io/docs/en/cli#--colors) (note the s) is used to force highlighting in non-TTY
- also, properly format package.json example as JSON, including the
"scripts" section
- and add a test:watch script for context, making more explicit the
difference between non-watch and watch mode
Follow-up to #385 , related to #319, #366 . Though this documentation does make me wonder whether it makes sense to have `--watch` as a default. It's much more …
> (docs): improve test watch mode docs

- README.md
- src/templates/react.ts
- the React template and docs for it had --env=jsdom explicitly set,
but there's no need to do this, as [Jest uses JSDOM by default](https://jestjs.io/docs/en/configuration#testenvironment-string) already
- setting it a second time in CLI also [overrides any custom configs](https://jestjs.io/docs/en/cli#options)
Docs seemed to be introduced in 4296413d8af48efbfccae4814178294fba847673 and template in #68 . This seems to have matched the templating of CRA v1, but this [was changed in CRA v2](https://github.com/facebook/create-react-app/blob/master/CHANGELOG-2.x.md#the-default-jest-environment-was-changed-to-jsdom). I'm guessing CRA may have defaulted to `node` under-the-hood in v1 but I'm not really sure (did not investigate history any further). `tsdx` seemed to never default to `node`, so …
> (clean): remove --env=jsdom as JSDOM is Jest's default

- test/jest.config.json
- default is jsdom, which we don't need
- also fix missing newline at EOF
Wrote this a while ago, but decided not to PR earlier as it didn't speed up tests _at all_ locally o.o Figured I should PR it now as it's related to #396 , can decide whether to close or merge now.
I guess this is still good to have for _correctness_ of tests, even if doesn't actually optimize anything. It might optimize windows tests on CI, as those seem to be slower than the rest but 🤷‍♂ 
<hr>
Also think this will be the last of my PRs for the day, was really on a roll today getting in lots of changes I had in-progress 😅 (though most of them were small)
> (optim/test): use node testEnvironment

- package.json
- yarn.lock
- and install it as a devDep
- doctoc is used in the README ToC and listed in comment, but wasn't
a devDep or used in any internal scripts
Follow-up to #397 . Please merge after that one and after #398 , which I split out from this PR.
The big thing that's not so helpful about running `doctoc` on pre-commit as that it won't abort the commit if changes were made. It just adds new changes, but those haven't been staged yet so won't be included in the commit (unless you amend them in). Not sure what a better method may be that isn't overly complex 😕
> (docs): run doctoc on pre-commit

- src/constants.ts
- src/createRollupConfig.ts
- src/index.ts
- and use ensureDistFolder since that exists now
- and use async readJSON since most were converted before
Merges stuff from #130, #327 , #291 , #142 as they were all merged together at different times but changed some conventions in the codebase or DRY'd things up.
> (refactor): use path constants instead of custom resolveApp

- src/createBuildConfigs.ts
- src/index.ts
- src/types.ts
- add types for all options and use those types throughout the
build/watch code
- fix some incorrect types in a few places that became more obvious
or errors once types were added
- fix default target from 'web' (not an option) to 'browser'
- extract createBuildConfigs into a separate file as it's fairly long
and has some relatively complex code
- and refactor it a bit to make it a bit easier to read as well as
easier to type (and type cast)
Follow-up to #371 , which was extracted out of this before I finished. I originally started this after #367 as the added types would give a lot of extra confidence around options, which were previously `any` everywhere. This is also going to merge conflict quite hard against #367 .
There are two type casts I couldn't seem to get around here (guess it …
> (types/refactor): be more specific than 'any' in build code

- README.md
- similar to the ones that exist in [react-app-rewired](https://github.com/timarney/react-app-rewired/#rewire-your-app-) and [customize-cra](https://github.com/arackaf/customize-cra#-warning)
as, like CRA, changing TSDX internals is a fragile path
Related to https://github.com/jaredpalmer/tsdx/issues/389#issuecomment-568866380 , #379 . This escape hatch is being used quite a bit by TSDX users as seen in various issues, but I'm not sure if all are aware of the risks that inherently entails (as I detailed in https://github.com/jaredpalmer/tsdx/issues/389#issuecomment-568866380). Those risks should be more explicit, as this may catch users off-guard, especially during updates, as even a patch update could break usage inside `tsdx.config.js`.
Plugins could at least pin a peer dependency and …
> (docs): add warning to tsdx.config.js usage

- src/index.ts
- fs.outputFile will create any directories that don't already exist
- also remove extraneous ensureDistFolder w/ try-catch in build command
Follow-up to https://github.com/jaredpalmer/tsdx/pull/402#discussion_r361822746 . Was going to add this to that PR but it got merged in before I could
> (refactor): replace ensureDistFolder with fs.outputFile

- src/createRollupConfig.ts
- not sure why this change was made in that PR as it was unrelated to
the rest, but it broke some things related to Babel usage and maybe
other things
- e.g. babel macros were not included per #413
- and it used `tslib` instead of adding babel helper functions
- add a comment of why it seems like the target is overridden to esnext
- though I am not sure of the original reasoning, as it has existed
since very early versions of TSDX, see #130 comments
Fixes #413 
Whether TS should transpile to target or Babel should is a good question to raise, but for now this just reverts the breaking change.
Should probably document in the README that `tsconfig` target is ignored and that users should use Babel's `preset-env` to configure the target instead.
Should also probably add more tests around …
> (fix): revert #130's breaking change of tsconfig options

- README.md
Hey, thanks for `tsdx` and all of the latest changes! Spotted what seems to be a typo in one of the newer examples. Here's a quick PR to fix.
> Fix onFailure example

- README.md
It is a good idea to have a reference to the `contributing guidelines` as part of the docs which the users may miss out if otherwise.
> [Docs]: Added a reference to contributing guidelines as part of the docs

- README.md
- src/index.ts
Revert "default jest watch unless in CI" PR #366
we decided to revert this behavior in https://github.com/jaredpalmer/tsdx/issues/408
closes https://github.com/jaredpalmer/tsdx/issues/408
> Revert "default jest watch unless in CI" PR #366

- .github/workflows/nodejs.yml
closes https://github.com/jaredpalmer/tsdx/issues/424#issuecomment-573202098
also begins Node 13 in preparation for for Node 14 release in April (goes LTS in Oct this year)
recheck https://github.com/jaredpalmer/tsdx/pull/422 once merged
> Deprecate Node 8 support

- .github/workflows/nodejs.yml
- README.md
Adding `--runInBand` which runs the test in a series instead of in parallel IIRC. This is what I believe was causing the race conditions
> Run tests in series with --runInBand

- README.md
- package.json
- src/index.ts
- src/messages.ts
- src/templates/basic.ts
- src/types.ts
- src/utils.ts
- yarn.lock
Fixes https://github.com/jaredpalmer/tsdx/issues/432
There was a few ways I could have approached this, so let me know if there's something more ideal.
To test:
1. Build. 
2. Change Node version to < 10 - `nvm use 8.11.3`
3. Run `node /dist/index.js create foo`, select any template – observe error
```
Unsupported Node version! Your current Node version (v8.11.3) does not satisfy the requirement of Node >=10.
```
4. Change Node version to >=10 - `nvm use 10.17.0`
5. Run `node /dist/index.js create bar`, select any template – observe success.
> (fix) Enforce Node version for tsdx create, update documentation to express requirement.

- templates/basic/tsconfig.json
- templates/react-with-storybook/tsconfig.json
- templates/react/tsconfig.json
- test/fixtures/build-default/tsconfig.json
- test/fixtures/build-invalid/tsconfig.json
- test/fixtures/build-withConfig/tsconfig.json
- tsconfig target is always overwritten to ESNext by TSDX, and then
the rest of the transpilation is done by @babel/preset-env
- having templates with target set gives the false impression that
target can be freely configured
- also remove from tests as it's unused there
See #415 for more about why the target is overwritten by TSDX
> (remove): redundant/confusing tsconfig target in templates

- README.md
- as of v0.9, custom Babel configs are merged with TSDX's transforms
- remove language about Babel entirely from comparison docs as Babel
support does not entail JS support (and at least some JS is already
supported anyway)
See https://github.com/jaredpalmer/tsdx/issues/443#issuecomment-578141998 and further comments that noticed this outdated language & were confused by it.
> (docs/fix): remove outdated language about custom Babel configs

- src/babelPluginTsdx.ts
- previously, if preset-env were not found in the user's presets,
their presets would be overwritten by a single preset-env entry
- now it properly merges their presets with an entry for preset-env
Fixes #443 
I _think_ this is good, but still need to create a test set-up for custom Babel configs. This requires installing some dependencies for automated tests. The `withConfig` `tsdx.config.js` fixture also requires installing some deps for automated tests and is currently a manual test (which means it isn't tested frequently -- I haven't tested it once in all my PRs), so would like to get that to be auto too.
> (fix): ensure Babel presets are merged

- src/babelPluginTsdx.ts
- src/createEslintConfig.ts
- tsconfig.json
- noUnusedParameters, noImplicitReturns, and noFallthroughCasesInSwitch
- improve typings for 1 unused parameter and 1 implicit return
- also remove noImplicitAny as that's redundant with strict: true
This is the same level of strictness as in the templates and I believe the highest level of strictness (I use the same level in my own libraries too).
The description of `noImplicitReturns` is a bit different from the name, not sure if it would've helped with something like #371 or not.
> (types): enforce stricter typings

- src/index.ts
- previously, TS, TSX, and JS were checked, but not JSX
Fixes #143 . Credits to @sisp for finding this and providing the suggested solution there. A PR hadn't ever been made and that issue's a bit old; this is related to #473 and #443 so figured it should be done sooner rather than later.
> (fix): check for JSX extension for entry files

- src/index.ts
- test/fixtures/build-withConfig/errors/ErrorDev.js
- test/fixtures/build-withConfig/errors/ErrorProd.js
- test/fixtures/util.js
- test/utils/psKill.js
- JS & JSX are already supported in tsdx build, so this is just adding
some better parity in tsdx test
- more JS & JSX support also means better support for gradual TS
migrations
- prior to this, JS & JSX files wouldn't be linted unless explicitly
included with a glob or something
- extensions is also only configurable via CLIEngine, .eslintrc
doesn't currently support it
- fix errors & warnings in JS test files as TSDX dogfoods its own lint
functionality
I'm currently adding TSDX in https://github.com/agilgur5/react-signature-canvas while migrating it to TS and this came up as frustration. Related to #486
> (feat): support JS & JSX files in tsdx lint

- src/createJestConfig.ts
- JS & JSX are already supported in tsdx build, so this is just adding
some better parity in tsdx test
- more JS & JSX support also means better support for gradual TS
migrations
- JS + JSX spec files should also be ran, not just TS + TSX
- run them with babel-jest, which is jest's default
- changing transform meant babel-jest wasn't run on them anymore
- notably, TSDX itself has tests written in JS, so TSDX would need
this to dogfood itself
- also get coverage from JS + JSX files too
I'm currently adding TSDX in https://github.com/agilgur5/react-signature-canvas while migrating it to TS and these all came up as frustrations. Related to #383 which is also about parity for build vs. test
> (feat): support JS & JSX files in tsdx test

- package.json
- src/createRollupConfig.ts
- src/env.d.ts
- src/index.ts
- yarn.lock
- transpileOnly default being the wrong type was found as a result of
the better typing
I originally made this as a follow-up to #407 , as `prog` is passed around as an argument there (and is `any` without these types), but that hasn't gotten a response in almost a month now 😐 😐
So figured I'd separate it out.
Just as a note note, the `@types/sade` package was reviewed by DT, but never got a response from the maintainer, https://github.com/lukeed/sade/issues/27#issuecomment-554268697
> (types): add @types/sade, fix transpileOnly default

- package.json
- personally, I often forget to yarn build before yarn test and that
means I'm testing stale changes
- would be good to have a way to run jest --watch, but that would
optimally require programmatic access to the CLI engine, which
needs some refactoring
Alternative to #492 . Please read that issue for more on test perf improvements we can make to TSDX.
This isn't as robust as #492 but is significantly faster and works the same way as `yarn lint`.
> (test): always run build before running tests

- src/index.ts
- before if your jest.config.js had an error in it, the try/catch would
just ignore it and pretend like your jest.config.js didn't exist
- this caused me a lot of confusion as to why my customizations
seemingly weren't being read at all
- instead of try/catching a MODULE_NOT_FOUND, check if it exists first,
and only then do parsing
- and let it throw an error if there is one, don't cover it up
Ran into this while making https://github.com/agilgur5/react-signature-canvas/pull/42/ as well, specifically https://github.com/agilgur5/react-signature-canvas/commit/8f124fe2be66b1e2d38d3844ca21ebf1221e56c4
Related to #483 which also had a silent parsing error due to an overbroad try/catch -- should really remove those from the codebase as they cause lots of confusing headaches to users
> (fix): jest config parsing shouldn't silently fail on error

- src/deprecated.ts
- src/index.ts
- templates/basic/tsconfig.json
- templates/react-with-storybook/tsconfig.json
- templates/react/tsconfig.json
- test/fixtures/build-default/tsconfig.json
- test/fixtures/build-invalid/tsconfig.json
- test/fixtures/build-withConfig/tsconfig.json
- rootDir needed to be changed to ./src because the previous ./ caused
type declarations to be generated in dist/src/ instead of just dist/
- the moveTypes function handled moving the declarations back into
dist/, but occassionally had errors moving .d.ts files
- particularly in CI and for projects with many of them
- declarationMap (*.d.ts.map) files would also have issues due to
the hackiness of moveTypes, setting to rootDir to './src' is one
of the necessary steps in fixing them
- deprecate moveTypes and add a warning with instructions if it is used
when a rootDir of './' is detected
- add notes about a deprecation window in the comments
<hr>
Split out from #488 and **built on top of #500 (please merge that first)** . 
- Per https://github.com/jaredpalmer/tsdx/pull/500#issuecomment-5836 …
> (fix): set rootDir to './src', not './'. deprecate moveTypes

- package.json
- yarn.lock
- object-hash v2.0.2 adds/fixes support for async functions
- rpts2 v0.26.0 upgrades object-hash to v2.0.2
- rpts2 currently bundles several of its dependencies, so they can't be
overridden manually and that's also why the object-hash change isn't
visible in the yarn.lock file
- previously, TSDX users who wanted to use rollup plugins (via
tsdx.config.js) that use async/await internally (e.g.
rollup-plugin-copy, rollup-plugin-url, rollup-plugin-visualizer,
rollup-plugin-smart-asset, etc, etc, etc), would run into
'Unknown object type "asyncfunction"' from object-hash as rpts2
hashes the rollup config itself for caching
- the only fix was to hackily override the rpts2 config in
tsdx.config.js (which requires brittle copy+paste as its config
isn't exposed) and then use a config option of …
> (fix): upgrade rpts2 / object-hash to support async rollup plugins

- src/createRollupConfig.ts
When custom `tsconfig` is used (e.g. `tsdx build --tsconfig tsconfig.build.json`), it is ignored in `createRollupConfig`.
For example, this causes bug in reach-ui build https://github.com/reach/reach-ui/issues/434. They use `tsconfig.build.json`, which is being ignore and the build files are missing `Object.defineProperty(exports, '__esModule', { value: true });`.
> Respect custom tsconfig path for esModuleInterop

- src/createJestConfig.ts
Master has a new regexp for Jest which breaks tests that reference JSON at some point in the dependency chain. This is a fix.
The regexp `.(js|jsx)` matches `.json` which means Jest attempts to load JSON files as JS modules. Since they aren't modules, Jest fails.
> fix: anchor regexps in Jest transforms for proper JSON handling

- README.md
- these docs actually predate the CI=true [addition](https://github.com/jaredpalmer/tsdx/pull/366) & [removal](https://github.com/jaredpalmer/tsdx/pull/421), not sure
why they said it runs in interactive mode
This was mentioned in https://github.com/jaredpalmer/tsdx/issues/270#issuecomment-584949460
> (fix/docs): `test` script doesn't run Jest in interactive mode

- src/index.ts
- previously they would show build command too
- either change them to watch or remove them if extraneous
> (fix): watch examples should only show watch command

- package.json
- src/index.ts
- yarn.lock
- if TSDX were installed directly from git, the `prepare` script would
for some reason fail on these events
- but they wouldn't error when run internally
- when Rollup was upgraded, then they started erroring
- also remove the unnecessary await in front of watch
So this fixes, partially, #512 's issue with the `prepare` script erroring out.
The event type issues might be related to `@types/node` changes like mentioned in #542, but idk, I didn't investigate remotely.
Also supersedes #295 and #317, which were probably failing due to the old missing `.d.ts` errors that were fixed with #504
> (deps/fix/types): upgrade rollup & fix event type issues

- package.json
- src/env.d.ts
- yarn.lock
- basically skipLibCheck: false should pass
- Babel declaration shouldn't have function braces and should have a
return type
- enquirer had some typings changes in [2.3.4](https://github.com/enquirer/enquirer/blob/master/CHANGELOG.md#234---2020-01-13), seems to be due to
changes in @types/node
Partially mentioned in https://github.com/jaredpalmer/tsdx/issues/529#issuecomment-594383051, though I found these separately/unintentionally while writing #544
> (fix/types): fix internal & external declaration errors

- package.json
- src/createJestConfig.ts
- src/index.ts
- test/jest.config.json
- --config will now be parsed shallow merged with the defaults,
just like package.json.jest already is
- previously adding --config to tsdx test would result in jest
outputting a usage prompt (I believe due to the second --config
that's added internally) and then the somewhat cryptic
"argv.config.match is not a function"
- if --config is detected, it will be parsed, merged, and then
deleted from argv so that this error doesn't occur anymore
Also dogfood `tsdx test` internally (this was the last thing needed for it to be possible) & improve Jest config typings
Fixes #150 , or rather what's left of it after #229 .
> (feat): support custom jest config paths via --config

- package.json
- yarn.lock
- none of them are used internally as dependencies or necessary as
peerDeps or used in tests
- chokidar-cli was added from an outdated PR and was only used as
a devDep; removed the one usage and dep itself
Fixes #197 . Supersedes #534
> (deps): remove unused cross-env, cross-spawn, chokidar-cli

- src/createRollupConfig.ts
- src/utils.ts
- test/fixtures/build-withTsconfig/tsconfig.base.json
- test/fixtures/build-withTsconfig/tsconfig.json
- use ts.readConfigFile to properly parse a commas and comments from
tsconfig instead of just trying to readJSON
- use ts.parseJsonConfigFileContent to properly parse `extends` and
get recursive compilerOptions
- add tests for all of the above use cases
- add them to build-withTsconfig which changes declarationDir;
should only work if TSDX properly parses the tsconfig
NOTE: this is only necessary for internal, TSDX-specific parsing of
tsconfig.json. rollup-plugin-typescript2 already handles these options,
but internal options like esModuleInterop etc are also used & parsed
independently of rpts2
Fixes #483 ~with its own suggestion, eventually getting to https://github.com/facebook/create-react-app/pull/7248 as the solution~ **EDIT**: that only solved commas and comments, `extends` needed …
> (fix): parse tsconfig extends, trailing commas, and comments

- src/createRollupConfig.ts
- test/fixtures/build-withTsconfig/tsconfig.base.json
- test/tests/tsdx-build.test.js
- it's a property of compilerOptions, not of overall tsconfig
- i.e. tsconfig.compilerOptions.esModuleInterop
- because this was incorrectly read, Rollup's esModule would always
be set to `undefined`, and Rollup would then default to `true`
- so esModuleInterop still wasn't being respected properly, I just
shifted the defaults when I incorrectly patched this :/
(test): add tests for the default tsconfig as well as for when it's
explicitly set to false
Fixes #469 . Actually this was unintentionally fixed by me a short while ago when I updated #489 , but this improves the syntax and adds tests
This is a follow-up on bugs in #327
> (fix): correctly read tsconfig esModuleInterop

- test/fixtures/build-withTsconfig/src/tsconfig.json
- test/tests/tsdx-build.test.js
- this never had tests for it, so ensure it's properly read
- make sure extends works, that an override works, and that paths
are correctly resolved
Basically ensure that #436 works
> (test): ensure custom --tsconfig path is correctly read

- src/createRollupConfig.ts
- test/fixtures/build-default/src/index.ts
- test/fixtures/build-default/src/syntax/jsx-import/JSX-A.jsx
- test/fixtures/build-default/src/syntax/jsx-import/JSX-B.jsx
- test/fixtures/build-default/src/syntax/jsx-import/JSX-import-JSX.jsx
close #523 
Add JSX extension to rollup `@rollup/plugin-node-resolve` plugin 
[The default extensions value](https://github.com/rollup/plugins/blob/b6621262e284057e5740089388ffdcc6c391998d/packages/node-resolve/src/index.js#L25) doesn't include the `.jsx` and It causes an error when import `jsx` from `js` file.
> Add JSX extension to @rollup/plugin-node-resolve options

- src/templates/basic.ts
- so library users can actually view source, add breakpoints there,
etc, etc and not only view types and dist files
Co-authored-by: Anton Gilgur <agilgur5@gmail.com>
Updated version of #252 with credit to original author. See https://github.com/jaredpalmer/tsdx/pull/252#issuecomment-599875270 and #494 for more context on why this is good to support
> Add 'src' to package.json files to improve source maps

- .github/workflows/nodejs.yml
- yarn install already builds, so we can skip the build step of these
scripts and run the post-build step of each instead
> (optim/ci): don't build a second time for lint or test

- .github/workflows/nodejs.yml
- this was added as an attempt to fix persistent CI errors that were
occurring due to the now deprecated `moveTypes()` function
- now that those have been fixed, this is no longer needed and should
have a small speed bump by removing this
- though it's possible --runInBand fixed a different CI error that
happened less frequently: `EPERM` on creating directories on
Windows, not sure, will find out
Basically a revert of #429 since #504 fixed the root cause behind most of the CI issues. If the Windows `EPERM` errors start happening again, we can revert this revert and then we'll know the `--runInBand` flag actually fixes it and that it's some type of race condition or something.
This was split out from #621 where CI passed a couple times with these changes
> (ci): remove experimental --runInBand as tests pass now

- test/fixtures/build-default/test/blah.test.ts
- test/fixtures/build-withConfig/test/blah.test.ts
- test/fixtures/build-withTsconfig/test/blah.test.ts
- there was probably some intent to use them for tests or for testing
`tsdx test` in the past, but they're currently wholly unused
- and get picked up by Jest unless ignored or otherwise skipped
> (clean): remove unused fixture test directories

- .github/workflows/nodejs.yml
- via [bahmutov/npm-install](https://github.com/bahmutov/npm-install)
- it handles all the cache steps, yarn vs. npm, OS differences, etc
> (ci/optim): add caching for yarn install

- src/babelPluginTsdx.ts
- src/createRollupConfig.ts
- these have been commented out for a long time now
- babel-plugin-transform-replace-expressions also isn't in the
dependencies either
- they were borrowed from microbundle afaik, but both support babelrc
nowadays; I think these defines are better configured there than
with flags anyway
> (clean): remove all references to --define

- src/env.d.ts
- these either aren't directly used in the code or are outdated and no
longer used in general
> (clean): remove some unnecessary internal declarations

- src/babelPluginTsdx.ts
- I was reading this and was confused which "preset" and "idx" it was
talking about (despite having worked on some of the code here
myself), so just make it more explicit
> (refactor): make preset-env variable naming more explicit

- .eslintignore
- jest.config.js
- package.json
- fix jest.config.js formatting errors
- ignore dist/ (and the default of node_modules)
Split out from #646 where I realized when editing the `jest.config.js` that it wasn't being linted/formatted.
This also starts another conversation -- shouldn't `tsdx lint` or the scripts in the templates default to `'./'` and not just `src test`? `src test` already misses things like `example` and `stories` as well as `.eslintrc.js`, `jest.config.js`, and any other root files or root directories.
Personally I think it should default to `'./'` and we'll need an `.eslintignore` or symlink to `.gitignore` for the templates then too since we need to ignore all `node_modules` (at root and at `example`) as well as `dist/`.
See also #517 that ESLint by default does not use `.gitignore` for ignores for some …
> (format): format all files, not just src/ and test/

- jest.config.js
- src/deprecated.ts
- templates/basic/tsconfig.json
- templates/react-with-storybook/tsconfig.json
- templates/react/tsconfig.json
- test/e2e/fixtures/build-default/test/some-test.test.ts
- test/e2e/fixtures/build-default/test/testUtil.ts
- test/e2e/fixtures/build-default/types/blar.d.ts
- test/e2e/tsdx-build-default.test.js
- `include` means all files that should be compiled, and the test dir
should definitely not be compiled
- this was causing issues where declarations were being output into
dist/ for all files in test/
- that shouldn't happen and it means `build` was unnecessarily
slowed down in order to process test/ files
- default `exclude` that was added of *.spec/*.test files,
originally for co-located tests, ended up making most test/ dir
files excluded too, but not, say, test utils that don't have a
.spec or .test suffix
- this was also causing errors with the `rootDir: './src'` change as
the test/ dir is outside of the rootDir
- problem wasn't the rootDir, but that the test/ dir shouldn't be
compiled or processed in any way
(test): ensure test/*.test.ts and test/*.ts files are correctly
excluded …
> (fix): remove faulty tsconfig.json include of test dir

- src/index.ts
- another thing that was missed in #130
- these sets are already done in normalizeOpts, no need to redundantly
perform them again
- fortunately this wasn't inconsistent with normalizeOpts, so no
harm done before this got out
Co-Authored-By: Kotaro Sugawara <kotarella1110@gmail.com>
<hr>
Follow-up to https://github.com/jaredpalmer/tsdx/pull/669#discussion_r405222739 and https://github.com/jaredpalmer/tsdx/pull/130#issuecomment-610716225
> (clean): remove redundant set of watch opts

- package.json
- yarn.lock
- `ms` dep was removed in df39d021440a5d2a, but not its
@types/ counterpart
- @types/ms was added in 70337566f88421 which also removed the only
usage of `ms`
- and the function that it was in that was removed was unused anyway
<hr>
`ms` was removed in #57, but not `@types/ms` .
`@types/ms` was added in #54 which also removed the only usage of `ms`.
> (deps/clean): remove unused @types/ms devDep

- package.json
- src/env.d.ts
- yarn.lock
- external @types/ are overridden by the package's own internal
typings, so any @types/ packages on top of that are extraneous
- and are usually deprecated too; all are in this case
- execa has had its own typedefs since v2
- the @types/execa package is very dated at v0.9
- ora has had its own typedefs since v3.2
- so @types/ora v3.2 is just a stub
- ansi-escapes has had its own typedefs since v4
- @types/ansi-escapes v4 is just a stub
- camelcase has had its own typedefs since v5.2
- @types/camelcase v5.2 is just a stub
- pin camelcase to v5.2+ from 5.0 to ensure it's a version with
internal typings
- ora also had an unnecessary internal re-declaration too
- as did ansi-escapes and camelcase
<hr>
(docs/types): add comments to some remaining declarations
- clarify why some of these …
> (deps/types/clean): remove extraneous typings

- package.json
- it's used in `tsdx create`, definitely not a devDep
- surprised that this hasn't been reported as a bug before, but
probably because it's a subdep of another dep so it finds its way
into most folks' node_modules anyway
<hr>
Oversight from #433 where it was added as a devDep instead of a dep.
Looks like that only made it into v0.13, so a v0.13.x patch is enough to fix
Incidental finding while upgrading other deps to Node 10+ (<tbd insert PR ref here>)
> (fix/deps): semver should be a dep, not a devDep

- src/createBuildConfigs.ts
- src/createRollupConfig.ts
- src/deprecated.ts
- src/index.ts
- every other emission is just a duplicate -- no need to spend compute
time to make duplicates
- even for the upcoming multi-entry, the same types are emitted for
each entry as the compiler just emits types for everything in the
`tsconfig` `include`
- fixes a long-standing bug with the deprecated moveTypes() function
that would occasionally cause types to not be properly output
- this was actually due to moveTypes() being run multiple times in
parallel (as well as the types themselves being emitted multiple
times in parallel)
- hence the EEXIST and ENOENT filesystem errors being thrown, as
that directory was being changed multiple times in parallel
- race conditions, fun!
- now they're only emitted once and only moved once, so no problems!
- also fixes a bug with an initial version of …
> (optim/fix): only emit type declarations once

- README.md
- while the docs do say these are run fairly directly, recently folks
seem to be particularly confused about how to configure Jest
- so explicitly mention `jest.config.js` and `.eslintrc.js` to make
that a bit more clear
- don't mention `package.json` options as I think that should be
implicitly implied enough now
- and because ESLint config works a bit differently in the two
cases (see [existing issue](https://github.com/jaredpalmer/tsdx/issues/514))
- and more explicitly say that all `tsdx test` flags are forwarded to
Jest
- also add links to "its own config" for each of the Babel, Jest, and
ESLint subsections so people can look at the source quickly if they
want
- the Babel one is a bit harder to read though
- and specify the merge behavior for each, i.e. shallow or deep
- and the …
> (docs): add Jest and ESLint subsections to Customization

- templates/basic/README.md
- templates/react-with-storybook/README.md
- templates/react/README.md
These haven't gotten any attention in a while and I forgot they existed for a bit (I don't use `create` myself). Bring them up to speed:
- (docs): update outdated Jest info in template READMEs
- follow-up to #536 
- (docs): remove version/permalink refs in template READMEs
- relates to #679 , #545 
- (docs): improve consistency in template READMEs
- follow-up to #360
- (docs): remove duplicative "Using the Playground" section
- (docs): add GitHub Actions info to template CI READMEs
- follow-up to #457 
- (docs): basic template README should be like React ones
> Update template docs: remove dated Jest info, improve consistency between all 3, add GitHub Actions docs

- templates/basic/tsconfig.json
- templates/react-with-storybook/example/tsconfig.json
- templates/react-with-storybook/tsconfig.json
- templates/react/example/tsconfig.json
- templates/react/tsconfig.json
- test/e2e/fixtures/build-default/tsconfig.json
- test/e2e/fixtures/build-invalid/tsconfig.json
- test/e2e/fixtures/build-withTsconfig/tsconfig.base.json
- test/integration/fixtures/build-options/tsconfig.json
- test/integration/fixtures/build-withBabel/tsconfig.json
- test/integration/fixtures/build-withConfig/tsconfig.json
- there are many issues about TS path aliases not fully "working", so
they should be removed from the templates until they are completely
"working"
- instead of shipping templates with a partially "broken" and
confusing configuration enabled
- especially confusing to users because editors will auto-complete
with the absolute path instead of the relative path
- and the fact that these paths are unresolved at build or test time
means that it's not understood that this is "broken" until later in
the process
- this is a *very* common misconception with TS users that `paths`
rewrites/transforms imports during compilation, but it actually does
not change any absolute paths to relative, it leaves them as is
- it just resolves type information to help on platforms that import
differently
- …
> (fix): templates should not have baseUrl or paths set

- README.md
Per https://english.stackexchange.com/a/588/27261
> (docs): Comparison to -> with

- src/index.ts
ref: https://github.com/jaredpalmer/tsdx/commit/a2e4b782cd71b0f7692768329b27fd189591348f, follow-up to #536
> fix/help: test command no longer runs Jest in watch mode

- src/createRollupConfig.ts
Fixes https://github.com/formik/tsdx/issues/757
Change-Id: I998648be8181371ec14e23a3096dc3b4ac731957
> optim: only check types once

- package.json
- src/messages.ts
Currently, the URLs pointing to the repo/issues are not uniform or correct.
It's not a huge deal since it seems all redirects are current working correctly,
but consistency is nice
> Update help channels to point to formium org

- templates/basic/.github/workflows/main.yml
- templates/react-with-storybook/.github/workflows/main.yml
- templates/react/.github/workflows/main.yml
[actions/cache@2](https://github.com/actions/cache/releases/tag/v2.0.0) has been released and comes with some useful updates.
> deps: upgrade actions/cache to v2 in all templates

- src/index.ts
- website/components/video.js
- website/nextra.config.js
- website/pages/_app.js
- website/pages/_document.js
- website/postcss.config.js
- website/tailwind.config.js
- with `yarn lint --fix`
- formatting error is from 8b148ce
- with `yarn lint --fix`
- formatting errors are from b09e195
- these were unable to be auto-fixed, so I had to manually fix them
- lint errors are from b09e195
One is from #734, the rest are from #765 .
This was causing CI errors for basically every PR afterward, mentioned in https://github.com/formium/tsdx/pull/762#pullrequestreview-450003239 and #789 
Not sure why `nextra` has some of these lint errors built into their examples (lack of `React`, `noreferrer`, etc), though [the project](https://github.com/shuding/nextra) does explicitly say that it is not production ready. Perhaps worth an upstream PR or two.
I plan to merge this myself, but in case someone else decides to beforehand, please ensure to **rebase** (_not_ squash …
> Fix formatting and lint errors from previous PRs

- src/templates/react-with-storybook.ts
- templates/react-with-storybook/.storybook/main.js
- templates/react-with-storybook/.storybook/preview.js
- templates/react-with-storybook/README.md
- templates/react-with-storybook/src/index.tsx
- templates/react-with-storybook/stories/Thing.stories.tsx
With the release of [Storybook v6](https://storybook.js.org/releases/6.0), there are [updates to be made](https://storybook.js.org/releases/6.0) to migrate from v5.3 and allow the `react-with-storybook` template take advantage of the latest features, i.e. built-in Typescript support and new story format.
> update react-with-storybook template for Storybook v6

- .github/workflows/nodejs.yml
- package.json
- yarn.lock
Motivation:
https://github.com/atlassian/yarn-deduplicate#why-is-this-necessary
Benefits:
Smaller & less nested node_modules
less deps are loaded into node when running dev stuff
It's good to run this command after every deps changes
> deps: add deduplicate script and apply yarn-deduplicate

- package.json
- yarn.lock
- transform-runtime is not used
- its functionality will instead be added by the newer/better
babel-plugin-polyfill-regenerator in [a future commit/PR](https://github.com/formium/tsdx/pull/795)
- move it to devDep as there is an integration test for it
- syntax-dynamic-import is not used
- and it's also included in @babel/preset-env anyway
- these were added in #208 to
support `@wessberg/rollup-plugin-ts` but were not rolled back when
that was rolled back in #287
In-line above, #795 for `transform-runtime` replacement, #208 and #287 for addition of plugins and lack of removal during rollback.
I had noticed `transform-runtime` was unused in https://github.com/formium/tsdx/issues/547#issuecomment-601392928 but hadn't fully investigated till now and found `syntax-dynamic-import` along the …
> clean/deps: remove unused Babel plugins: transform-runtime, dynamic-import

- README.md
- [`tsdx lint`](https://github.com/formium/tsdx/pull/99) is a thing now
- [`tsdx create`](https://github.com/formium/tsdx/commit/9010ecbda5121dba74c04edebd2b18ef447eda3e) is a thing
- [`tsdx.config.js`](https://github.com/formium/tsdx/pull/183) is a thing now
- "last year or so" in reference to microbundle is outdated now and the
differences have grown since then, so be softer on the language of
similarities
- TSDX now has good support for JS as well, I put in [a]((https://github.com/formium/tsdx/pull/474) good [bit](https://github.com/formium/tsdx/pull/486) of [work](https://github.com/formium/tsdx/pull/487)
to make that possible, especially for gradual migrations and partial
codebases
- and some contributors [helped](https://github.com/formium/tsdx/pull/524) as well
Lint added in #99 …
> docs: update features and comparison with changes from past year

- .github/dependabot.yml
- per bug report
- duplicate config because anchors/aliases aren't supported, which is a
bit annoying
Fixes #849 , follow-up to #846
> fix/deps: dependabot YAML doesn't support anchors/aliases

- README.md
- for when you need to make some small changes to the internal code and
forking is a bit too extreme of an option
- hopefully patch-package means folks get their changes in faster
without waiting for PRs and means folks don't have to use outdated
forks etc
- it was first recommended by Shawn in issues then strongly recommended
by Jared and I've recommended it a few times too for smaller changes
- Quoting Jared: "Yes, to documenting patch-package as ultimate
escape hatch"
Referenced in:
- https://github.com/formium/tsdx/issues/110#issuecomment-518079299
- https://github.com/formium/tsdx/issues/389#issuecomment-568785862
- https://github.com/formium/tsdx/pull/436#issuecomment-578239297
- https://github.com/formium/tsdx/issues/509#issuecomment-586663005
- …
> docs: add `patch-package` reference to Customization section

- README.md
- src/index.ts
- test/e2e/fixtures/lint/file-with-lint-warnings.ts
- test/e2e/tsdx-lint.test.ts
Fixes #853 
Works in a similar way to the --max-warnings flag in ESLint.
If `tsdx lint` finds more than `--max-warnings` number of warnings, it exits with a non-zero code. Otherwise, it exits with 0.
> Add `--max-warnings` flag to `tsdx lint`

- templates/basic/tsconfig.json
- templates/react-with-storybook/tsconfig.json
- templates/react/tsconfig.json
- test/e2e/fixtures/build-default/tsconfig.json
- test/e2e/fixtures/build-invalid/tsconfig.json
- test/e2e/fixtures/build-withTsconfig/tsconfig.base.json
- test/integration/fixtures/build-options/tsconfig.json
- test/integration/fixtures/build-withBabel/tsconfig.json
- test/integration/fixtures/build-withConfig/tsconfig.json
- as defaults to the templates' tsconfigs
- these are now recommended by TS to be set to true, which can be
seen in the TSConfig Reference and @tsconfig/recommended
- c.f. https://www.typescriptlang.org/tsconfig and
https://www.npmjs.com/package/@tsconfig/recommended
- also add to all fixtures
- yea some centralization/extends or dogfooding create would help
reduce all this duplication
- skipLibCheck is a big perf gain, though it seems to only affect
`tsc --noEmit` usage and rollup-plugin-typescript2 seems to ignore it
- I have an existing issue open on the matter
- forceConsistentCasingInFileNames is a no-brainer to help avoid a bug
that is easy to make and hard to debug
- also add a trailing comma for ease of use and better diffing
- not to fixtures though, because there is a test for …
> Add skipLibCheck, noEmit, consistentCasing, and lots of comments to template tsconfigs

- src/babelPluginTsdx.ts
- test/integration/fixtures/build-withBabel/.babelrc.js
- test/integration/fixtures/build-withBabel/src/styled.tsx
- test/integration/tsdx-build-withBabel.test.ts
- if babel-plugin-macros is first, macros get applied first
- babel-plugin-styled-components says it should be placed first, but
unfortunately all user plugins are added after TSDX plugins
- unknown how changing this ordering could impact lots of code out
there, but could be very breaking.
- moving to a preset instead would mean this is more in user
control
- but we can change it so macros are added first and so one can use
styled-components/macro instead as a workaround
- based on babel-plugin-styled-component's code, docs, and output in
detail, I think its ordering conflict may be with
babel-plugin-annotate-pure-calls, which so happens to be the first
plugin in babelPluginTsdx
- maybe this should be last given that other plugins can change
functions etc
(test): update styled-component …
> (fix): change plugin order to make styled-components/macro work

- README.md
- src/index.ts
I spent ten minutes with adding globs and comma-separated paths before giving up going into the issues and searching/finding #175 / #367. 
Maybe delete the `(s)` until the issue is resolved to prevent other people from doing the same. :)
> multi-entry: temporarily change docs to singular "module"

- templates/basic/.github/workflows/main.yml
- templates/react-with-storybook/.github/workflows/main.yml
- templates/react/.github/workflows/main.yml
Thanks for adding GH actions to the templates,
it's awesome and greatly reduces overhead of adding CI on new packages.
I always end up needing to read the damm docs again for every project 🙈 
**nitpick** fix on this PR:
`CI=true` is already declared at runner level.
docs: [default-environment-variables](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables)
> fix: remove redundant CI env from workflow steps

- README.md
- TSDX itself has a Node 10 requirement on package.json#engines now,
so this is fairly explicit already and not limited to `tsdx create`
anymore either
- Node 8 was also EoL quite a while ago at the end of last year, so this
isn't quite as important of a note anymore
Follow-up to #678 where I think I decided to leave it in for some reason, but I didn't comment why so I don't remember.
Removes a doc entry from #433
> docs: remove reference to Node 10+ req for create

- .github/workflows/nodejs.yml
- Node 13.x was EoL at the beginning of June per
https://github.com/nodejs/Release
- similarly we just recently updated @types/node to v14
`@types/node` was updated to v14 in #879
> ci: update matrix to use Node 14 instead of Node 13

- .github/workflows/nodejs.yml
- templates/basic/.github/workflows/main.yml
- templates/basic/README.md
- templates/react-with-storybook/.github/workflows/main.yml
- templates/react-with-storybook/README.md
- templates/react/.github/workflows/main.yml
- templates/react/README.md
- have been using this internally for about 6 months and I've personally
contributed [bugfixes](https://github.com/bahmutov/npm-install/pull/37) and [optimizations](https://github.com/bahmutov/npm-install/pull/43) to it, so should be good to
use by general users too
- it's a good bit less configuration, which is particularly better for
beginners, but even for advanced users, it means that improvements
are shared out to all users
- I also [recommended it in an actions/cache issue](https://github.com/actions/cache/issues/94#issuecomment-674398895) about needing too
much config already too, which I wouldn't have done if I weren't
confident in its usage now
- this properly caches node_modules by using ~/.npm or Yarn's cache dir
as recommended, instead of `node_modules` itself, which is not
- …
> Improve template CI: add matrix testing, use `bahmutov/npm-install`

- templates/react-with-storybook/.storybook/main.js
> feat: type-check stories during Storybook build

- package.json
- yarn.lock
This solves the following warning on yarn install
eslint-config-react-app@5.0.2" has incorrect peer dependency "eslint-plugin-react-hooks@1.x".
> Use compatible eslint-config-react-app and eslint-plugin-react-hooks.

- package.json
- src/babelPluginTsdx.ts
- test/e2e/fixtures/build-default/src/index.ts
- test/e2e/tsdx-build-default.test.ts
- yarn.lock
When importing modules from `lodash/fp` we get breaking imports since `babel-plugin-transform-rename-import` renames all `lodash` imports to `lodash-es` for the esm build.
e.g `import mergeAll from 'lodash/fp/mergeAll';` ends up being imported like `import mergeAll from 'lodash-es/fp/mergeAll'` and we get an error since `lodash-es/fp` doesn't exist.
With this fix we rename all `lodash-es/fp` imports to `lodash/fp` and we get the correct imports in the final esm build.
> fix: don't replace lodash/fp imports with lodash-es/fp

- package.json
- test/e2e/tsdx-build-options.test.ts
- yarn.lock
Bumped into #888/#892 when creating a new repo, and the workaround mentioned [here](https://github.com/formium/tsdx/issues/892#issuecomment-702449484) didn't work for me.
This patch brings in the permanent fix from ezolenko/rollup-plugin-typescript2#243. Tested by yarn linking tsdx across repos, and the build looks to be working ok with this change.
Guess dependabot would have eventually updated this dep, but figured it was important enough to do ASAP?
> fix/deps: upgrade rollup-plugin-typescript2 to fix cache issue

- .github/dependabot.yml
- several of the dependencies in the tree are only there because they
are peerDeps, and not because we directly depend on them
- they should only be upgraded in tandem with the dep(s) they are
peers of and pretty much never in isolation
- Greenkeeper made several PRs for peers which previously caused an
erroneous/buggy update of `@types/jest` to 25 many months before Jest
was upgraded to 25
- and honestly those Greenkeeper PRs for peers had confused me a
good deal too
- #462 was a previous erroneous PR due to Greenkeeper updating peers, which was reverted in #470 
- This directly addresses some of my previous confusion from `eslint-config-react-app` peers in https://github.com/formium/tsdx/pull/640#issuecomment-702894150 / https://github.com/formium/tsdx/pull/642#issuecomment-702892887 / …
> deps: ignore dependabot for peer dependencies

- website/pages/customization.md
_Maintainer edit_:
Closes #844
> fix: relative links in website to absolute links
